#!/usr/bin/python2


__root="__testing"
virtualenv="virtualenv2"

class DuplicateIdError(Exception):
    pass
class MkdirError(Exception):
    pass
class ArchiveError(Exception):
    pass
class MakeError(Exception):
    pass
class MoveError(Exception):
    pass


def execute(command,wd,ErrorClass,shell=False):
    print "executing :\033[31m"+" ".join(command)+"\033[0m at \033[33m",wd,"\033[0m"
    import subprocess
    with open(wd+"/"+command[0]+".out","w+") as fh:
        p=subprocess.Popen(command,shell=shell,cwd=wd,stderr=subprocess.PIPE,stdout=fh)
    p.wait()
    if(p.returncode !=0):
        raise ErrorClass("Error executing '"+" ".join(command)+"': "+p.stderr.read())


def createArchive(tag):
    import os,shutil
    root=os.path.abspath(os.path.dirname(__file__))
    wd=root+"/"+__root+"/"+tag
    if(os.path.exists(wd)):
        raise DuplicateIdError

    try:
        os.makedirs(wd)
        os.makedirs(wd+"/PyFR")
    except Exception as e:
        raise MkdirError
    try:
        shutil.move(root+"/__inbox/"+tag,wd+"/PyFR")
    except Exception as e:
        raise MoveError(str(e))

    execute(("tar","-z","-x","--file",tag),wd=wd+"/PyFR",ErrorClass=ArchiveError)
    os.symlink("../../scripts/Makefile",wd+"/Makefile")
    os.symlink("../../scripts/prepareAndSendReport",wd+"/prepareAndSendReport")
    execute(("make","scheduleReportSend"),wd=wd,ErrorClass=MakeError,shell=True)


if(__name__=="__main__"):
    import sys
    createArchive(sys.argv[1])
    
