#!/bin/bash


ROOT=$(dirname $(readlink -f $0))

CASE_NAME=euler_vortex_2d
MSH_FILE=${CASE_NAME}*.pyfrm
SOLS=${CASE_NAME}*.pyfrs
INI=*.ini


for SOL_FILE in ${SOLS[@]}
do
	VTU_FILE=$(basename $SOL_FILE .pyfrs).vtu
	echo "creating $VTU_FILE"

	pyfr-postp convert $MSH_FILE $SOL_FILE $VTU_FILE

done
for p in ${ROOT}/plot-*
do

	PNGBASE=$(basename $p |sed 's/plot-//')
	for SOL_FILE in ${SOLS[@]}
	do
		VTU_FILE=$(basename $SOL_FILE .pyfrs).vtu
		PNG_FILE=${PNGBASE}-$(basename $SOL_FILE .pyfrs).png
		echo "plotting $PNG_FILE"
		$p -i $VTU_FILE -o $PNG_FILE
	done

done
