#!/bin/bash

ROOT=$(dirname $(readlink -f $0))
WD=${PWD}

. installRoot/bin/activate

mkdir -p tests
cd tests

log 'begin-create'


PRECISION=("dp" "sp")
PLATFORMS=("OpenMP" "CUDA" "OpenCL")
PARALLEL=("serial" "parallel")

TEST_REPO=${ROOT}/../Tests
EXAMPLES=$(ls ${TEST_REPO})

CBLAS='/usr/lib64/libcblas.so'

for e in ${EXAMPLES[@]}
do
	mkdir $e
	pushd ${PWD}>/dev/null
	cd $e
	cp -r $TEST_REPO/$e/${e}.msh $TEST_REPO/$e/${e}.ini ./ 
	for p in ${PRECISION[@]}
	do
		mkdir $e-$p
		pushd ${PWD}>/dev/null		
		cd $e-$p
		cp ../${e}.msh ./
		if [ "$p" == "sp" ];then
			sed 's/^precision.*/precision = single/' ../${e}.ini >${e}.ini
		else
			sed 's/^precision.*/precision = double/' ../${e}.ini >${e}.ini

		fi

		for a in ${PLATFORMS[@]} 
		do
			mkdir $e-$p-$a
			pushd ${PWD}>/dev/null
			cd $e-$p-$a
			cp ../${e}.msh ./
			if [ $a == OpenMP ];then
				sed "s_.*cblas-st.*_cblas-st = ${CBLAS}_" ../${e}.ini >${e}.ini
			else
				cp ../${e}.ini ./
			fi

			for q in ${PARALLEL[@]}
			do
				mkdir $e-$p-$a-$q
				pushd ${PWD}>/dev/null
				cd $e-$p-$a-$q
				cp ../${e}.msh ./${e}-${p}-${a}-${q}.msh
				cp ../${e}.ini ./${e}-${p}-${a}-${q}.ini
				${ROOT}/getRun ${e} ${p} ${a} ${q} ${e}-${p}-${a}-${q} ${WD} >run
				${ROOT}/getPostProcess ${e} ${p} ${a} ${q} ${e}-${p}-${a}-${q} $WD >runPP
				chmod +x ./run ./runPP
				#rm ${e}.msh ${e}.ini			
				popd >/dev/null
			done
			rm ${e}.msh ${e}.ini			
			popd >/dev/null
			
		done
		rm ${e}.msh ${e}.ini
		popd >/dev/null
	done
	rm ${e}.msh ${e}.ini
	popd >/dev/null
done

log 'end-create'
